### PR TITLE
librarify log

### PR DESCRIPTION
**Pull request by pittma**

### CODE REVIEW

**Comment by pittma** [comment]
I have no idea what to do about this CI failure.

**Comment by jonlamb-gh** [comment]
> I have no idea what to do about this CI failure.

Interesting, I'm seeing the armv7 target failure on master too:
```
---- history::test::overwritten_paired_wall_clock_time_drops_buddy_entry stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `83`,
 right: `82`', src/history.rs:1434:9
```

**Comment by jonlamb-gh** [comment]
> > I have no idea what to do about this CI failure.
> 
> Interesting, I'm seeing the armv7 target failure on master too:
> 
> ```
> ---- history::test::overwritten_paired_wall_clock_time_drops_buddy_entry stdout ----
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `83`,
>  right: `82`', src/history.rs:1434:9
> ```

I haven't chased this one down yet, but it seems likely related to a change in alignment, this patch seems to fix the issue:

```diff
diff --git a/fenced-ring-buffer/src/lib.rs b/fenced-ring-buffer/src/lib.rs
index 05c718d..a69a87d 100644
--- a/fenced-ring-buffer/src/lib.rs
+++ b/fenced-ring-buffer/src/lib.rs
@@ -157,6 +157,8 @@ pub trait Entry: Copy + PartialEq {
 }
 
 /// An entry or double entry that has just been overwritten
+//#[repr(align(32))]
+#[cfg_attr(target_pointer_width = "32", repr(align(32)))]
 #[derive(PartialEq, Copy, Clone, Debug)]
 pub enum WholeEntry<E>
 where
```

**Comment by pittma** [comment]
> this patch seems to fix the issue:
Thanks, giving that a go.

**Review by jonlamb-gh — APPROVED** [review]

**Pull request merged**
